DATA MANIPULATION

In [18]:
import pandas as pd

In [19]:
students = pd.DataFrame({
    'Name': ['Neha', 'Ravi', 'Sam', 'Anu'],
    'City': ['Kochi', 'Chennai', 'Kochi', 'Chennai'],
    'Score': [85, 90, 78, 65],
     'Age' : [20,18,21,23]
})

avg_by_city = students.groupby('City')['Score'].mean()
print(avg_by_city)

City
Chennai    77.5
Kochi      81.5
Name: Score, dtype: float64

In [20]:
print(students.groupby(['City', 'Name'])['Age'].median())

City     Name
Chennai  Anu     23.0
         Ravi    18.0
Kochi    Neha    20.0
         Sam     21.0
Name: Age, dtype: float64

In [60]:
df=pd.DataFrame({
    'Name': ['Neha','Sam', 'Ravi', 'Sam', 'Anu'],
    'City': ['Kochi', 'Kochi', 'Chennai', 'Kochi', 'Chennai'],
    'Score': [85, 90, 78,90, 65],
     'Age' : [20,21, 18,21,23],
     'Gender': ['F', 'M', 'M', 'M', 'F']})
print(df)

   Name     City  Score  Age Gender
0  Neha    Kochi     85   20      F
1   Sam    Kochi     90   21      M
2  Ravi  Chennai     78   18      M
3   Sam    Kochi     90   21      M
4   Anu  Chennai     65   23      F

In [28]:
print(df.isnull().sum())

Name     0
City     0
Score    0
Age      0
dtype: int64

In [29]:
print("No of duplicate rows:", df.duplicated().sum())

No of duplicate rows: 1

In [30]:
print(df.drop_duplicates())

   Name     City  Score  Age
0  Neha    Kochi     85   20
1   Sam    Kochi     90   21
2  Ravi  Chennai     78   18
4   Anu  Chennai     65   23

In [38]:
print(df.describe(include="all"))

       Name   City      Score       Age
count     5      5   5.000000   5.00000
unique    4      2        NaN       NaN
top     Sam  Kochi        NaN       NaN
freq      2      3        NaN       NaN
mean    NaN    NaN  81.600000  20.60000
std     NaN    NaN  10.502381   1.81659
min     NaN    NaN  65.000000  18.00000
25%     NaN    NaN  78.000000  20.00000
50%     NaN    NaN  85.000000  21.00000
75%     NaN    NaN  90.000000  21.00000
max     NaN    NaN  90.000000  23.00000

In [40]:
print(df.corr(numeric_only=True))

          Score       Age
Score  1.000000 -0.338077
Age   -0.338077  1.000000

In [41]:
print(df['Score'].mode())

0    90
Name: Score, dtype: int64

In [42]:
print(df.groupby('City')['Score'].agg(['max', 'mean']))

         max       mean
City
Chennai   78  71.500000
Kochi     90  88.333333

DATA TRANSFORMATIONS

In [43]:
df['Percent of marks']= df['Score']*(90/100)

In [64]:
print(df)

   Name     City  Score  Age  Gender
0  Neha    Kochi     85   20  Female
1   Sam    Kochi     90   21    Male
2  Ravi  Chennai     78   18    Male
3   Sam    Kochi     90   21    Male
4   Anu  Chennai     65   23  Female

In [47]:
df['Grade']=df['Score'].apply(lambda x: 'Pass' if x>=85 else 'Fail')
#print(df)

In [49]:
df['Age']= df['Age'].astype(int)

In [55]:
df.rename(columns={'Marks': 'Score', 'Years': 'Age'}, inplace=True)

In [61]:
df['Gender']=df['Gender'].map({'M': 'Male', 'F': 'Female'})

In [62]:
print(df['Gender'])

0    Female
1      Male
2      Male
3      Male
4    Female
Name: Gender, dtype: object

In [65]:
pd.crosstab(df['City'], df['Score'])

Score    65  78  85  90
City
Chennai   1   1   0   0
Kochi     0   0   1   2

In [66]:
df.groupby('City')['Score'].mean()

City
Chennai    71.500000
Kochi      88.333333
Name: Score, dtype: float64

In [68]:
print("Std dev: ",df['Score'].std())
print("Variance: ", df['Score'].var())

Std dev:  10.502380682492898
Variance:  110.30000000000001

In [69]:
df.corr(numeric_only=True)

          Score       Age
Score  1.000000 -0.338077
Age   -0.338077  1.000000

In [70]:
city_stats= df.groupby('City')['Score'].agg(['mean', 'count'])
print(city_stats)

              mean  count
City
Chennai  71.500000      2
Kochi    88.333333      3

In [71]:
print(city_stats.sort_values('mean', ascending=False))

              mean  count
City
Kochi    88.333333      3
Chennai  71.500000      2